### ISSUE TITLE
12 UNIMPLEMENTED: unknown service events.Events

### ISSUE THREAD

**Issue by dougg0k** [onflow/flow-go#1761]
Hi,

I've been trying to fetch events data from mainnet1 forward with gRPC calls and I have been getting this error. I tried different clients, same thing.

```
    err: {
      "type": "Error",
      "message": "12 UNIMPLEMENTED: unknown service events.Events",
      "stack":
          Error: 12 UNIMPLEMENTED: unknown service events.Events
              at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
              at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:343:36)
              at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
              at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
              at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
              at processTicksAndRejections (node:internal/process/task_queues:78:11)
      "code": 12,
      "details": "unknown service events.Events",
      "metadata": {
        "content-type": [
          "application/grpc"
        ]
      }
    }
```

```
syntax = "proto3";

import "google/protobuf/timestamp.proto";

package events;

service Events {
  rpc GetEventsForHeightRange(GetEventsForHeightRangeRequest) returns (GetEventsForHeightRangeResponse) {}
}

message GetEventsForHeightRangeRequest {
  string type = 1;
  uint64 start_height = 2;
  uint64 end_height = 3;
}

message GetEventsForHeightRangeResponse {
  message Result {
    bytes block_id = 1;
    uint64 block_height = 2;
    repeated Event events = 3;
    google.protobuf.Timestamp block_timestamp = 4;
  }
  repeated Result results = 1;
}

message Event {
  string type = 1;
  bytes transaction_id = 2;
  uint32 transaction_index = 3;
  uint32 event_index = 4;
  bytes payload = 5;
}
```

```
import * as grpc from "@grpc/grpc-js";
import * as protoLoader from "@grpc/proto-loader";

const protoObject = protoLoader.loadSync(
		path.join(__dirname, 'events.proto'),
		{
			keepCase: true,
			longs: String,
			enums: String,
			defaults: true,
			oneofs: true,
		},
);
const definition = grpc.loadPackageDefinition(protoObject);
const client = new definition.events.Events(
     "access-001.mainnet1.nodes.onflow.org:9000",
     grpc.credentials.createInsecure(),
);
client.getEventsForHeightRange(
	{
		type: eventType,
		startHeight: startBlock,
		endHeight: endBlock,
	},
	(err, data) => {
		console.log(err);
                console.log(data);
	},
);
```
When I try with mainnet7 forward, the message is a bit different `"message": "12 UNIMPLEMENTED: ",` with date and server in metadata obj `"date": ["Fri, 10 Dec 2021 15:29:42 GMT" ], "server": ["envoy"]`

**Comment by dougg0k** [comment]
I opened in a repo that make more sense. https://github.com/onflow/flow/issues/724
