### ISSUE TITLE
gRPC Ping call error

### ISSUE THREAD

**Issue by dougg0k** [onflow/flow-go#1765]
Hi,

I've been trying to call the rpc Ping in `access-001.candidate4.nodes.onflow.org:9000`, `access-001.candidate5.nodes.onflow.org:9000` and `access-001.candidate6.nodes.onflow.org:9000`.

But it returns this error.
```
Error: 2 UNKNOWN: could not ping execution node: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.197.17.191:9000: connect: connection refused"
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:343:36)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 2,
  details: 'could not ping execution node: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.197.17.191:9000: connect: connection refused"',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }
}
```
While in all other candidate and most mainnet urls seems to be working. Was it because it wasn't implemented in those? Though it doesn't seem like it, given the error.

`GetEventsForHeightRange` in those endpoints is working. I need because some NFTs token were implemented from the node `candidate4`.

Edit: For now, this works and will do.
```
return new Promise((resolve, reject) => {
	client.ping({}, (err, data) => {
		if (err) {
			const isUnavailable =
				err?.code === 14 || err?.message.includes("io exception");
			if (isUnavailable) {
				reject(false);
			}
			client.getNetworkParameters({}, (err, data) => {
				if (err) {
					reject(false);
				}
				resolve(true);
			});
		}
		resolve(true);
	});
});
```

Edit2: I am getting a similar error when trying to fetch event range from node `candidate6`.

```
  err: {
      "type": "Error",
      "message": "13 INTERNAL: failed to retrieve events from execution node: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 35.197.17.191:9000: connect: connection refused\"",
      "stack":
          Error: 13 INTERNAL: failed to retrieve events from execution node: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 35.197.17.191:9000: connect: connection refused"
              at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
              at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:343:36)
              at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:430:34)
              at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
              at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
              at processTicksAndRejections (node:internal/process/task_queues:78:11)
      "code": 13,
      "details": "failed to retrieve events from execution node: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 35.197.17.191:9000: connect: connection refused\"",
      "metadata": {
        "content-type": [
          "application/grpc"
        ]
      }
    }
```
Still `rpc GetNetworkParameters` works for them all.

**Comment by dougg0k** [comment]
Well, I am testing with `getEventsForHeightRange` and it seems that candidate5 is up, but not candidate6, all the others are working.

```
{
  "code": 13,
  "details": "failed to retrieve events from execution node: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 35.197.17.191:9000: connect: connection refused\"",
  "metadata": {
    "content-type": [
      "application/grpc"
    ]
  }
}
```
