### ISSUE TITLE
getAccount(0x0) or any non-existing account sends back internal error

### ISSUE THREAD

**Issue by j1010001** [onflow/flow-go#3387]
## 🐞 Bug Report

`getAccount(0x0)` or any non-existing account, fails with `UnexpectedErrorFromCause` and sends back stack trace. 

```
[Error Code: 1101] cadence runtime error Execution failed:
error: internal error: get storage used failed: failed to get storage used: [Error Code: 1201] account not found for address 0000000000000001
goroutine 31 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x64
[github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(..](http://github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(..).)
[github.com/onflow/cadence@v0.25.0/runtime/errors/errors.go:139](http://github.com/onflow/cadence@v0.25.0/runtime/errors/errors.go:139)
[github.com/onflow/cadence/runtime/interpreter.(*Interpreter).RecoverErrors(0x14000c61520](http://github.com/onflow/cadence/runtime/interpreter.(*Interpreter).RecoverErrors(0x14000c61520), 0x105b84530)
```

## What is the severity of this bug?

Should have  (It would be better if we do this before we ship, but it's OK if we don't (product functions without this, but it's a better user experience).

## Expected behaviour

report a user error, instead of returning internal error

## Specifications

Reported on flow-go Mainnet 19 (0.27)

## Additional context

Reported by @Bluesign

**Comment by j1010001** [comment]
Note: The solution is for the FVM to indicate to Cadence that the account does not exist, and then report a user error, instead of reporting an non-existing account is unexpected.
