### ISSUE TITLE
[FVM] updating contract returns an implementation error

### ISSUE THREAD

**Issue by sideninja** [onflow/flow-go#3729]
## 🐞 Bug Report

When trying to remove an existing contract I get an implementation error where as far as I understand a user error should be returned.

## Reproduction steps

Run the emulator and try to remove an existing contract.

## Expected behaviour

Should return a user error?

## Error

```
[ef5ceb] [Error Code: 1056] error caused by: 1 error occurred:
	* transaction invocation failed when executing transaction: [Error Code: 1101] cadence runtime error: Execution failed:
error: internal error: remove account contract code failed: removing contract failed: [Error Code: 1056] (RemoveContract) is not authorized: removing contracts requires authorization from specific accounts
goroutine 42437 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/onflow/cadence/runtime/errors.NewUnexpectedErrorFromCause(...)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/errors/errors.go:132
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).RecoverErrors(0xc008cdf980, 0x254fb20)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter.go:492 +0x14e
panic({0x20b1180, 0xc0094bd340})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/onflow/cadence/runtime/stdlib.newAuthAccountContractsRemoveFunction.func1({0x0, {0xc00925bac0, 0x1, 0x1}, {0xc00925b940, 0x1, 0x1}, 0xc00925b930, {{0x2705b50, 0xc009076c80}, ...}, ...})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/stdlib/account.go:1955 +0x515
github.com/onflow/cadence/runtime/interpreter.(*HostFunctionValue).invoke(0xc009076c80?, {0x0, {0xc00925bac0, 0x1, 0x1}, {0xc00925b940, 0x1, 0x1}, 0xc00925b930, {{0x2705b50, ...}, ...}, ...})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/function.go:255 +0x55
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).invokeFunctionValue(0xc008cdf980?, {0x271b978, 0xc009263f08}, {0xc00925bab0?, 0x1?, 0xc00925b9c0?}, {0xc00925baa0?, 0x1?, 0x14988b5?}, {0xc00925b940, ...}, ...)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_invocation.go:122 +0x17e
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitInvocationExpression(0xc008cdf980, 0xc0092681c0)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_expression.go:873 +0x5cb
github.com/onflow/cadence/runtime/ast.AcceptExpression[...]({0x2712f60?, 0xc0092681c0}, {0x271eb90, 0xc008cdf980})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/ast/visitor.go:218 +0x29d
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).evalExpression(...)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_expression.go:248
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).VisitExpressionStatement(0xc0094d6410?, 0x174b208?)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_statement.go:561 +0x34
github.com/onflow/cadence/runtime/ast.AcceptStatement[...]({0x270edc0?, 0xc00925b820}, {0x271a840, 0xc008cdf980})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/ast/visitor.go:135 +0x495
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).evalStatement(0xc008cdf980, {0x270edc0?, 0xc00925b820})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_statement.go:57 +0x15e
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).visitStatements(0x15f61da?, {0xc00925b830?, 0x1, 0x15f5e1b?})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_statement.go:63 +0x68
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).invokeInterpretedFunctionActivated.func2()
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_invocation.go:168 +0x2d
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).visitFunctionBody(0xc008cdf980, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x15f2245?}, 0xc0094d66d0, {0x0, 0x0, ...}, ...)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter.go:726 +0x1a7
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).invokeInterpretedFunctionActivated(0xc008cdf980?, 0xc009210700?, {0xc00920ba10?, 0x1?, 0xc008cdf9e0?})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_invocation.go:164 +0x1a5
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).invokeInterpretedFunction(0xc008cdf980, 0xc009210700, {0xc00925ba50, {0xc00920ba10, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, ...})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_invocation.go:143 +0x1c5
github.com/onflow/cadence/runtime/interpreter.(*InterpretedFunctionValue).invoke(...)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/function.go:126
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).declareTransactionEntryPoint.func1({0xc00925ba50, {0xc00920ba10, 0x1, 0x1}, {0x0, 0x0, 0x0}, 0x0, {{0x0, 0x0}, ...}, ...})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter_transaction.go:107 +0x245
github.com/onflow/cadence/runtime/interpreter.(*HostFunctionValue).invoke(0x0?, {0x0, {0xc00920ba00, 0x2, 0x2}, {0x0, 0x0, 0x0}, 0x0, {{0x0, ...}, ...}, ...})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/function.go:255 +0x55
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).InvokeExternally(0x21e4340?, {0x271b978, 0xc009263d88}, 0xc009015700?, {0xc00920b9e0?, 0x2?, 0xc0094d6c48?})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter.go:434 +0x21e
github.com/onflow/cadence/runtime/interpreter.(*Interpreter).InvokeTransaction(0xc008cdf980, 0xc00920b9f0?, {0xc00920b9e0, 0x2, 0x2})
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/interpreter/interpreter.go:476 +0x2b6
github.com/onflow/cadence/runtime.(*interpreterTransactionExecutor).transactionExecutionFunction.func1(0xc008cdf980)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/transaction_executor.go:261 +0x29f
github.com/onflow/cadence/runtime.(*interpreterEnvironment).Interpret.func1()
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/environment.go:944 +0x9e
github.com/onflow/cadence/runtime.reportMetric(0xc0094d6f28, {0x2726550?, 0xc0001ed680?}, 0xc0094d6f10)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/runtime.go:201 +0x65
github.com/onflow/cadence/runtime.(*interpreterEnvironment).Interpret(0xc009017950, {0x2705b50, 0xc009076c80}, 0x0?, 0xc009263d58)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/environment.go:938 +0x105
github.com/onflow/cadence/runtime.(*interpreterTransactionExecutor).execute(0xc0092646c0)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/transaction_executor.go:218 +0x19f
github.com/onflow/cadence/runtime.(*interpreterTransactionExecutor).Execute.func1()
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/transaction_executor.go:75 +0x25
sync.(*Once).doSlow(0x70?, 0xc009205a40?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/onflow/cadence/runtime.(*interpreterTransactionExecutor).Execute(0xc0092646c0?)
	/Users/dapper/go/pkg/mod/github.com/onflow/cadence@v0.30.0/runtime/transaction_executor.go:74 +0x50
github.com/onflow/flow-go/fvm/runtime.WrappedCadenceExecutor.Execute({{0x2701060?, 0xc0092646c0?}})
	/Users/dapper/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221214175701-076c0fd2a2f9/fvm/runtime/wrapped_cadence_runtime.go:89 +0x27
github.com/onflow/flow-go/fvm.(*transactionExecutor).normalExecution(0xc006777d40)
	/Users/dapper/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221214175701-076c0fd2a2f9/fvm/transactionInvoker.go:282 +0x36c
github.com/onflow/flow-go/fvm.(*transactionExecutor).ExecuteTransactionBody(0xc006777d40)
	/Users/dapper/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221214175701-076c0fd2a2f9/fvm/transactionInvoker.go:189 +0x1e6
github.com/onflow/flow-go/fvm.(*transactionExecutor).execute(0xc006777d40)
	/Users/dapper/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221214175701-076c0fd2a2f9/fvm/transactionInvoker.go:161 +0x9a
github.com/onflow/flow-go/fvm.(*transactionExecutor).Execute(0xc006777d40)
	/Users/dapper/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221214175701-076c0fd2a2f9/fvm/transactionInvoker.go:122 +0x25
github.com/onflow/flow-go/fvm.Run({0x2701180?, 0xc006777d40})
	/Users/dapper/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221214175701-076c0fd2a2f9/fvm/fvm.go:39 +0xc2
github.com/onflow/flow-go/fvm.(*VirtualMachine).Run(_, {0x0, 0x186a0, 0xffffffffffffffff, 0x3e80, 0xf424000, 0x1312d00, {0x1, 0x1, 0x3e8, ...}, ...}, ...)
	/Users/dapper/go/pkg/mod/github.com/onflow/flow-go@v0.28.1-0.20221214175701-076c0fd2a2f9/fvm/fvm.go:120 +0xa4b
github.com/onflow/flow-emulator.(*Blockchain).executeNextTransaction.func1({0x2713320, 0xc00847da90}, 0x1, 0xc007f3cd80) 
```

**Comment by janezpodhostnik** [comment]
This is not as a scary error as it seems its just a normal error when trying to remove a contract when not authorized to do so: `removing contracts requires authorization from specific accounts`

Its just that the stack trace is attached due to cadence treating it as an unknown error https://github.com/onflow/cadence/blob/29c9723938e4a96defb746d403600ad5e9d91a67/runtime/interpreter/interpreter.go#L489. We should check if that can be changed.
